name = "toolkits-mcp"
main = "src/index.ts"
compatibility_date = "2024-09-23"

[[r2_buckets]]
binding = "TOOLKITS_BUCKET"
bucket_name = "toolkits-assets"

[vars]
GITHUB_OWNER = "ajfaysal"
GITHUB_REPO = "toolkits-mcp"
R2_PUBLIC_BASE_URL = "https://pub-754afb105d4d4297ae849b868850f2da.r2.dev"
